theme: Flavor
hexojs/site pull request #1689
Opened 2021-08-24 02:29 UTC by xtexChooser

- [x] I want to publish my theme on Hexo official website.
  - [x] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [x] `name` is unique.
  - [x] `link` URL is correct.
  - [x] `preview` URL is correct.
  - [x] `preview` URL web site is rendered correctly.
  - [x] Add a screenshot to `source/themes/screenshots`.
  - [x] Screenshot filename is same as value of `name`.
  - [x] Screenshot size is `800 * 500`.
  - [x] Screenshot file format is `png`.

2021-09-09 09:45 UTC, jiangtj commented
I found your preview link seems to be broken.

2021-09-10 13:25 UTC, xtexChooser commented
> I found your preview link seems to be broken.

what? Its my blog and I can open it correctly

2021-11-02 17:57 UTC, tomap approved these changes

2021-11-03 04:45 UTC, stevenjoezhang requested changes

2021-11-03 04:45 UTC, stevenjoezhang commented on source/_data/themes.yml
> +  preview: https://xtexx.ml/blog/2021-8-23-custom-theme/
<img width="773" alt="截屏2021-11-03 下午12 45 16" src="https://user-images.githubusercontent.com/16272760/140010991-d9ecd12c-cf3b-46cd-a238-304c98f4aba6.png">

The link returns 404 not found

2021-11-06 00:25 UTC, xtexChooser commented on source/_data/themes.yml
> +  preview: https://xtexx.ml/blog/2021-8-23-custom-theme/
Thanks, resolved

2021-11-06 03:19 UTC, merged

2021-11-06 03:20 UTC, xtexChooser commented
Thanks