Docs: add note on permalink
hexojs/site pull request #1734
Opened 2021-11-17 21:12 UTC by sukrosono

this commit intended to close hexo/#4663 .
cheers, happy coding :)

## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
  - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
  - [ ] `preview` URL is correct.
  - [ ] `preview` URL web site is rendered correctly.
  - [ ] Add a screenshot to `source/themes/screenshots`.
  - [ ] Screenshot filename is same as value of `name`.
  - [ ] Screenshot size is `800 * 500`.
  - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
  - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)
  - Languages:
  - [ ] `en` English
  - [ ] `ko` Korean
  - [ ] `pt-br` Brazilian Portuguese
  - [ ] `ru` Russian
  - [ ] `th` Thai
  - [ ] `zh-cn` simplified Chinese
  - [ ] `zh-tw` traditional Chinese

2021-11-18 07:04 UTC, SukkaW requested changes

2021-11-18 07:04 UTC, SukkaW commented on source/docs/front-matter.md
> +`permalink` | Overrides the default permalink of the post | `null` but keep remember permalink sould end with `/` or `.html`
```suggestion
`permalink` | Overrides the default permalink of the post. Permalink sould end with `/` or `.html` | `null`
```

2021-11-18 07:05 UTC, SukkaW commented
Also, would you mind adding this to all languages? Just copy the sentence in English to every languages' markdown file and will be fine.

2021-11-19 02:26 UTC, sukrosono commented
eh, my priority changes then. It should have my nationality languages too [id]. Maybe next year, but don't close this,

2021-11-19 07:33 UTC, SukkaW approved these changes

2021-12-15 17:16 UTC, yoshinorin approved these changes
Thank you :)

2021-12-15 17:16 UTC, merged